/**
 * One-time wallet generation script.
 * Derives 10 deterministic wallets from a single BIP-39 mnemonic.
 *
 * Run: npm run generate-wallets
 * Output: .env.wallets (gitignored)
 */

import { generateMnemonic, mnemonicToAccount, english } from 'viem/accounts';
import { writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, '../.env.wallets');

if (existsSync(OUT_FILE)) {
  console.error('❌ .env.wallets already exists. Delete it first if you want to regenerate.');
  console.error('   WARNING: Regenerating creates NEW addresses — you lose the old ones.');
  process.exit(1);
}

const mnemonic = generateMnemonic(english);

const wallets = Array.from({ length: 10 }, (_, i) => {
  const account = mnemonicToAccount(mnemonic, { addressIndex: i });
  // Access the HD key for private key extraction
  const hdKey = account.getHdKey();
  const pk = hdKey.privateKey
    ? Buffer.from(hdKey.privateKey).toString('hex')
    : null;

  if (!pk) throw new Error(`Failed to extract private key for index ${i}`);

  return {
    index: i,
    address: account.address,
    privateKey: `0x${pk}`,
    role: ['admin', 'minter', 'investor-a', 'investor-b', 'investor-c',
           'reporter', 'restricted', 'no-kyc', 'whale', 'spare'][i],
  };
});

const envLines = [
  `# Generated by: npm run generate-wallets`,
  `# Date: ${new Date().toISOString()}`,
  `# NEVER commit this file`,
  ``,
  `TEST_MNEMONIC="${mnemonic}"`,
  `TEST_RPC_URL=https://base-sepolia.drpc.org`,
  `DEPLOYER_PK=  # <-- fill this in: the 0x41521c37... deployer private key`,
  ``,
  ...wallets.flatMap(w => [
    `# ${w.index}: ${w.role}`,
    `TEST_WALLET_${w.index}_ADDRESS=${w.address}`,
    `TEST_WALLET_${w.index}_PK=${w.privateKey}`,
    ``,
  ]),
];

writeFileSync(OUT_FILE, envLines.join('\n'), 'utf-8');

console.log('\n' + '═'.repeat(60));
console.log('  🔐  NEXUS PROTOCOL — TEST WALLET GENERATION');
console.log('═'.repeat(60));
console.log('\n⚠️  SAVE THIS MNEMONIC — BACK IT UP NOW:');
console.log('\n  ' + mnemonic);
console.log('\n' + '═'.repeat(60));
console.log('\n📋  Wallet addresses to fund with 0.05 ETH each:');
console.log('   (Send Base Sepolia ETH from MetaMask — manual step)\n');
console.table(
  wallets.map(w => ({ '#': w.index, role: w.role, address: w.address }))
);
console.log('\n✅  Written to: tests/e2e/.env.wallets');
console.log('\nNext steps:');
console.log('  1. Add your DEPLOYER_PK to .env.wallets');
console.log('  2. Send 0.05 Base Sepolia ETH to each address above');
console.log('  3. Run: npm run seed-wallets');
