// Minimal ABIs for UI interaction — full ABIs generated by hardhat compile

export const STABLECOIN_ABI = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "pure" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "mint", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "burn", inputs: [{ name: "from", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "pause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unpause", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "paused", inputs: [], outputs: [{ type: "bool" }], stateMutability: "view" },
] as const;

export const YIELD_VAULT_ABI = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "totalAssets", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "convertToAssets", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "convertToShares", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewDeposit", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewWithdraw", inputs: [{ name: "assets", type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "previewRedeem", inputs: [{ name: "shares", type: "uint256" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "deposit", inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ name: "assets", type: "uint256" }, { name: "receiver", type: "address" }, { name: "owner", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "redeem", inputs: [{ name: "shares", type: "uint256" }, { name: "receiver", type: "address" }, { name: "owner", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "asset", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "oracle", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "transfer", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
] as const;

export const NAV_ORACLE_ABI = [
  { type: "function", name: "getLatestNAV", inputs: [], outputs: [{ name: "totalAssets", type: "uint256" }, { name: "timestamp", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getHistoryLength", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getNAVAt", inputs: [{ name: "index", type: "uint256" }], outputs: [{ type: "tuple", components: [{ name: "totalAssets", type: "uint256" }, { name: "timestamp", type: "uint256" }, { name: "reporter", type: "address" }] }], stateMutability: "view" },
  { type: "function", name: "postNAV", inputs: [{ name: "totalAssets", type: "uint256" }, { name: "timestamp", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const MINT_CONTROLLER_ABI = [
  { type: "function", name: "mintAllocation", inputs: [{ name: "minter", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "mintedAmount", inputs: [{ name: "minter", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "remainingAllocation", inputs: [{ name: "minter", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "setMintAllocation", inputs: [{ name: "minter", type: "address" }, { name: "ceiling", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "resetMintedAmount", inputs: [{ name: "minter", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "mint", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const RESTRICTION_LIST_ABI = [
  { type: "function", name: "isRestricted", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "restrict", inputs: [{ name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "unrestrict", inputs: [{ name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "batchRestrict", inputs: [{ name: "accounts", type: "address[]" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const KYC_REGISTRY_ABI = [
  { type: "function", name: "isVerified", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "getStatus", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "tuple", components: [{ name: "verified", type: "bool" }, { name: "expiry", type: "uint256" }, { name: "verifiedAt", type: "uint256" }] }], stateMutability: "view" },
  { type: "function", name: "setVerified", inputs: [{ name: "account", type: "address" }, { name: "expiry", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "revokeVerification", inputs: [{ name: "account", type: "address" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const RESERVE_TRACKER_ABI = [
  { type: "function", name: "getTotalReserves", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getLatestReserve", inputs: [], outputs: [{ type: "tuple", components: [{ name: "assetType", type: "string" }, { name: "amount", type: "uint256" }, { name: "timestamp", type: "uint256" }, { name: "reporter", type: "address" }] }], stateMutability: "view" },
  { type: "function", name: "getReserveCount", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getReserveHistory", inputs: [], outputs: [{ type: "tuple[]", components: [{ name: "assetType", type: "string" }, { name: "amount", type: "uint256" }, { name: "timestamp", type: "uint256" }, { name: "reporter", type: "address" }] }], stateMutability: "view" },
  { type: "function", name: "postReserve", inputs: [{ name: "assetType", type: "string" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const ACCREDITED_INVESTOR_ABI = [
  { type: "function", name: "isAccredited", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "setAccredited", inputs: [{ name: "account", type: "address" }, { name: "status", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "batchSetAccredited", inputs: [{ name: "accounts", type: "address[]" }, { name: "status", type: "bool" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const VAULT_FACTORY_ABI = [
  { type: "function", name: "getVaultCount", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getVault", inputs: [{ name: "index", type: "uint256" }], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "isVault", inputs: [{ name: "addr", type: "address" }], outputs: [{ type: "bool" }], stateMutability: "view" },
  { type: "function", name: "createVault", inputs: [{ name: "depositToken", type: "address" }, { name: "oracle", type: "address" }, { name: "name", type: "string" }, { name: "symbol", type: "string" }], outputs: [{ type: "address" }], stateMutability: "nonpayable" },
] as const;

// ---- Phase 2: Derivatives ----

export const PRINCIPAL_TOKEN_ABI = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maturity", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
] as const;

export const YIELD_TOKEN_ABI = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "maturity", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "yieldOwed", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "claimYield", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "nonpayable" },
] as const;

export const YIELD_SPLITTER_ABI = [
  { type: "function", name: "vault", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "pt", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "yt", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "maturity", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalVaultShares", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "split", inputs: [{ name: "vaultShares", type: "uint256" }], outputs: [{ name: "ptAmount", type: "uint256" }, { name: "ytAmount", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "unsplit", inputs: [{ name: "ptAmount", type: "uint256" }], outputs: [{ name: "vaultShares", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "redeemPT", inputs: [{ name: "ptAmount", type: "uint256" }], outputs: [{ name: "assets", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "redeemYT", inputs: [{ name: "ytAmount", type: "uint256" }], outputs: [{ name: "yieldAmount", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "distributeYield", inputs: [], outputs: [], stateMutability: "nonpayable" },
] as const;

export const CREDIT_VAULT_ABI = [
  { type: "function", name: "collateralVault", inputs: [], outputs: [{ type: "address" }], stateMutability: "view" },
  { type: "function", name: "collateralRatioBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "liquidationRatioBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "borrowRateBps", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "positions", inputs: [{ name: "user", type: "address" }], outputs: [{ name: "collateralShares", type: "uint256" }, { name: "debtNUSD", type: "uint256" }, { name: "lastAccrualTime", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "ltvRatio", inputs: [{ name: "borrower", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "collateralValue", inputs: [{ name: "borrower", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "currentDebt", inputs: [{ name: "borrower", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "availableLiquidity", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "depositCollateral", inputs: [{ name: "shares", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "borrow", inputs: [{ name: "nusdAmount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "repay", inputs: [{ name: "nusdAmount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdrawCollateral", inputs: [{ name: "shares", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "liquidate", inputs: [{ name: "borrower", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "fundLiquidity", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
] as const;

export const ETF_WRAPPER_ABI = [
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalNAV", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "pricePerToken", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allocationCount", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allocations", inputs: [{ name: "index", type: "uint256" }], outputs: [{ name: "vault", type: "address" }, { name: "weightBps", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "deposit", inputs: [{ name: "nusdAmount", type: "uint256" }], outputs: [{ name: "etfTokens", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "withdraw", inputs: [{ name: "etfTokens", type: "uint256" }], outputs: [{ name: "nusdAmount", type: "uint256" }], stateMutability: "nonpayable" },
] as const;

export const SWAP_GATEWAY_ABI = [
  { type: "function", name: "ethPrice", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "ethReserves", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "quoteBuyNUSD", inputs: [{ name: "ethWei", type: "uint256" }], outputs: [{ name: "nusdOut", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "quoteSellNUSD", inputs: [{ name: "nusdAmount", type: "uint256" }], outputs: [{ name: "ethOut", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "buyNUSD", inputs: [{ name: "minNUSDOut", type: "uint256" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "sellNUSD", inputs: [{ name: "nusdAmount", type: "uint256" }, { name: "minETHOut", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "buyVaultShares", inputs: [{ name: "vault", type: "address" }, { name: "minShares", type: "uint256" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "sellVaultShares", inputs: [{ name: "vault", type: "address" }, { name: "shares", type: "uint256" }, { name: "minETHOut", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "event", name: "BoughtNUSD", inputs: [{ name: "buyer", type: "address", indexed: true }, { name: "ethIn", type: "uint256" }, { name: "nusdOut", type: "uint256" }, { name: "price", type: "uint256" }] },
  { type: "event", name: "SoldNUSD", inputs: [{ name: "seller", type: "address", indexed: true }, { name: "nusdIn", type: "uint256" }, { name: "ethOut", type: "uint256" }, { name: "price", type: "uint256" }] },
] as const;
